name: Build plugin on Pull Request
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space (Ubuntu only)
      uses: jlumbroso/free-disk-space@main

    - name: Set up MPI
      uses: mpi4py/setup-mpi@master

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gcc-10 g++-10 make
        
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@main
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: scipion3
        python-version: "3.8"
    
    - name: Install Scipion
      working-directory: ${{ github.workspace }}/../
      run: |
        pip cache purge
        pip install --user scipion-installer
        python3 -m scipioninstaller -conda -noXmipp -noAsk scipion
    
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}

    - name: Install plugin from pull request
      working-directory: ${{ github.workspace }}
      run: |
        pip cache purge
        ../scipion/scipion3 installp -p . --devel
    
    # Currently, test script is being downloaded from scipion-chem, but that should be temporary
    # Ideally, the script might be included in scipion core to be able to import it,
    # or maybe host it in a separate repository common with useful scripts for all scipion plugins
    #- name: Run tests
    #  working-directory: ${{ github.workspace }}/${{ vars.FOLDER_WITH_VERSION }}
    #  run: |
    #    wget https://raw.githubusercontent.com/scipion-chem/scipion-chem/devel/pwchem/runTests.py
    #    python runTests.py ${{ github.workspace }}/../scipion/scipion3 ${{ vars.FOLDER_WITH_VERSION }} -noGPU -testData=testData.json
