name: master to pypi with comments and tag
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gcc-10 g++-10 libopenmpi-dev make
        
    - name: Checkout repository
      uses: actions/checkout@main
    
    - name: Set up MPI
      uses: mpi4py/setup-mpi@master
    
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'

    - name: Install Miniconda
      working-directory: ${{ github.workspace }}/../
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p miniconda/
        source miniconda/etc/profile.d/conda.sh
        conda update -n base -c defaults conda -y
    
    - name: Install Scipion
      working-directory: ${{ github.workspace }}/../
      run: |
        eval "$(miniconda/bin/conda shell.bash hook)"
        pip3 install --user scipion-installer
        python3 -m scipioninstaller -conda -noXmipp -noAsk scipion

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine Pillow
        pip install -r requirements.txt
    
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/* -c "{{ secrets.PYPI_COMMENT }}"
    
    - name: Get tag name
      id: variables
      env:
        FOLDER_WITH_VERSION: ${{ vars.FOLDER_WITH_VERSION }}
      run: |
        eval "$(miniconda/bin/conda shell.bash hook)"
        VERSION=$(python -c "import $FOLDER_WITH_VERSION; print('VERSION', 'v'+$FOLDER_WITH_VERSION.__version__)" | grep VERSION | sed "s/VERSION //g")
        echo "RELEASE_NAME=$VERSION" >> $GITHUB_OUTPUT
        echo "TAG_NAME=${VERSION#v}" >> $GITHUB_OUTPUT
    
    - name: Generate tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.variables.outputs.TAG_NAME }}
    
    - name: Create a GitHub release
      uses: ncipollo/release-action@main
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: ${{ steps.variables.outputs.TAG_NAME }}
